### PR TITLE
fix comment line number on server output

### LINKED ISSUE #80: Minor Bug: Nulls for filename and line number in final execution report.
First, let me say thank you for making this wonderful tool. I just discovered it today and it perfectly fills a gap that has been bothering me for some time: providing batched code review feedback to LLMs from a side-by-side diff. Your project deserves way more stars.

Now, for the report. When `difit` exits, I notice that the filename and line number for each comment is reported as `undefined`, which I assume is what JS null renders as into a string. Example:
```text
📝 Comments from review session:
==================================================
undefined:Lundefined
Might want to allow `WebFetch` and `WebSearch` for research on packages.
=====
undefined:Lundefined
We can drop the parenthetical "refer to" remarks, since the agent may not know about the other commands and will not be able to execute them, if it does.
=====
undefined:Lundefined
The `find` command does not respect `.gitignore` afaik. Not sure how useful this is. Would simply expect the `filesystem.rst` to be up-to-date.

Would be more useful to list the contents of `documentation/architecture/designs`.
``` 

By contrast, what I paste from the clipboard into Claude Code has the correct context:
```text
  .auxiliary/configuration/claude/commands/cs-design-python.md:L2
  Might want to allow `WebFetch` and `WebSearch` for research on packages.
  =====
  .auxiliary/configuration/claude/commands/cs-design-python.md:L14-L15
  We can drop the parenthetical "refer to" remarks, since the agent may not know about the other commands and will not be able to execute them, if it does.
  =====
  .auxiliary/configuration/claude/commands/cs-design-python.md:L25
  The `find` command does not respect `.gitignore` afaik. Not sure how useful this is. Would simply expect the `filesystem.rst` to be up-to-date.

  Would be more useful to list the contents of `documentation/architecture/designs`.
```

Obviously, this is a very minor issue, since the clipboard actually does have the context which the LLM needs. But, I could see this as being problematic if someone was trying to use this as a Claude Code hook or `!` command. (Possible timeout issues notwithstanding.)

### PR DESCRIPTION
**Pull request by yoshiko-pg**
- **refactor: use shared comment formatting utility for both client and server**
- **fix server output**

closes #80

### CODE REVIEW

File: src/client/App.tsx [hunk 1]
```diff
@@ -217,7 +217,18 @@ function App() {
...
+        id: c.id,
+        file: c.filePath,
+        line:
+          typeof c.position.line === 'number' ?
+            c.position.line
+          : [c.position.line.start, c.position.line.end],
+        body: c.body,
+        timestamp: c.createdAt,
+      }));
+      const data = JSON.stringify({ comments: transformedComments });
```
Comment (yoshiko-pg) [inline src/client/App.tsx:231]: The logic is duplicated, but with subsequent modifications, it will no longer be necessary to convert the DiffComment type into the Comment type in the first place.
